[project]
name = "pwnshop"
version = "0.0.0"
description = "CLI tooling for pwn.college challenges"
requires-python = ">=3.9"
authors = [{ name = "pwn.college" }]
dependencies = [
  "black",
  "click",
  "jinja2",
  "pyyaml",
  "rich",
]

[project.scripts]
pwnshop = "pwnshop:cli"
