name: Build Legacy Challenges
on:
  push:
    # branches: [ main, master ]
    # paths:
    #   - 'legacy/**'
  workflow_dispatch:

jobs:
  build-legacy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build legacy challenges
      run: |
        ./legacy/build.sh $(ls legacy/*/.git | sed 's|/\.git$||')

    - name: List all Docker images
      run: |
        docker images
